- README.md
Signed-off-by: Ricardo Koller <kollerr@us.ibm.com>
> Adding travis card

- tests/bats-core/LICENSE.md
Signed-off-by: Ricardo Koller <kollerr@us.ibm.com>
> Adding bats-core license file

- Makefile
This makes sure that the user is warned if their submodules are not in the expected state.
Signed-off-by: Dan Williams <djwillia@us.ibm.com>
> submodule warning

- README.md
> Added docker requirement version

- runnc-cont/runnc_cont.go
Signed-off-by: Ricardo Koller <kollerr@us.ibm.com>
> Adding --mem argument to runnc-cont

- nabla-lib/network/network_linux.go
Signed-off-by: Ricardo Koller <kollerr@us.ibm.com>
> Removing useless printf in network lib

- nabla-lib/network/network_linux.go
- nabla-lib/storage/storage_linux.go
- runnc-cont/runnc_cont.go
- runnc.go
> Fixed go issues and refactor

- runnc.go
> Error on using host network namespace in docker

- README.md
Signed-off-by: Sahil Suneja <sahilsuneja@gmail.com>
> TLS limitations ++

- runnc.go
> Added check for entrypoint nabla file

- Gopkg.toml
- runnc-cli/Makefile
- runnc-cli/README.md
- runnc-cli/create.go
- runnc-cli/delete.go
- runnc-cli/exec.go
- runnc-cli/kill.go
- runnc-cli/runnc.go
- runnc-cli/start.go
- runnc-cli/state.go
- runnc-cli/util.go
Initial check-in of main skeleton so others can build on top of it.
> Created initial skeleton of runnc-cli

- Makefile
- README.md
- runnc.go
> fix typos, whitespace

- .gitignore
- libcontainer/configs/config.go
- libcontainer/configs/defaults.go
- libcontainer/configs/spec.go
- libcontainer/container_nabla.go
- libcontainer/errors.go
- libcontainer/init_nabla.go
- runnc-cont/rumprun.go
- runnc-cont/runnc_cont.go
- tests/integration/run.bats
- util.go
- util_tty.go
- utils/convert.go
I'm not 100% on the json spec aspect of this. The code is working as is, with and without the `-m` flag being passed from docker.
Some of these changes are due to using VS Code. Which I think is using a gofmt plugin to make the changes. I can disable this if requested and unformat the files.
Opening it at this stage for feedback. I'm still evaluating the types of the arguments as I pass them around.
> WIP: Pass memory to runnc

- init.go
> Change print line to format

- Makefile
Addressing https://github.com/nabla-containers/runnc/issues/60
> Removed container integration tests temporarily

- libcontainer/factory_nabla.go
> Clarify the ID error

- README.md
> update readme to use v0.3 version

- libcontainer/process.go
- tests/integration/run.bats
- util_runner.go
Did initial manual testing and it is correctly editing the file so far.
Outstanding Questions:
- Not sure if this function is the way we want it handled, or if it would be better as a method on specs.Process
- Will running this as non-root cause problems?
Need to finish:
> add support for flag --oom-score-adj

- libcontainer/factory_nabla.go
> Fix missing /etc directory in rootfs

- libcontainer/configs/spec.go
> Initial memory minimum fix

- .travis.yml
- Makefile
- README.md
- tests/integration/helpers.bash
- tests/integration/run.bats
Initially converting run.bats to shellcheck format.
Todo:
> Shellcheck
